# Generated by Django 5.2.9 on 2025-12-08 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightup', '0003_course_donate_income_item_outcome_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='tribe',
            field=models.CharField(choices=[('阿美族', '阿美族'), ('泰雅族', '泰雅族'), ('排灣族', '排灣族'), ('布農族', '布農族'), ('卑南族', '卑南族'), ('魯凱族', '魯凱族'), ('鄒族', '鄒族'), ('賽夏族', '賽夏族'), ('達悟族', '達悟族'), ('邵族', '邵族'), ('噶瑪蘭族', '噶瑪蘭族'), ('太魯閣族', '太魯閣族'), ('撒奇萊雅族', '撒奇萊雅族'), ('賽德克族', '賽德克族'), ('拉阿魯哇族', '拉阿魯哇族'), ('卡那卡那富族', '卡那卡那富族'), ('其他', '其他')], max_length=10, verbose_name='族別'),
        ),
    ]
