# Generated by Django 5.2.8 on 2025-12-01 06:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightup', '0002_alter_family_options_alter_member_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('start_date', models.DateField(verbose_name='開始日期')),
                ('end_date', models.DateField(verbose_name='結束日期')),
                ('name', models.CharField(max_length=30, verbose_name='課程名稱')),
                ('account', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='學費')),
                ('consume', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='書費')),
                ('backup', models.TextField(blank=True, verbose_name='備註')),
            ],
            options={
                'verbose_name': '訓練課程',
                'verbose_name_plural': '訓練課程管理',
            },
        ),
        migrations.CreateModel(
            name='Donate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('name', models.CharField(max_length=30, verbose_name='奉獻者抬頭')),
            ],
            options={
                'verbose_name': '奉獻者',
                'verbose_name_plural': '奉獻者管理',
            },
        ),
        migrations.CreateModel(
            name='Income_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('name', models.CharField(max_length=30, verbose_name='名稱')),
                ('backup', models.TextField(blank=True, verbose_name='備註')),
            ],
            options={
                'verbose_name': '奉獻收入帳務項目',
                'verbose_name_plural': '奉獻收入帳務項目管理',
            },
        ),
        migrations.CreateModel(
            name='Outcome_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('name', models.CharField(max_length=30, verbose_name='名稱')),
                ('backup', models.TextField(blank=True, verbose_name='備註')),
            ],
            options={
                'verbose_name': '奉獻支出帳務項目',
                'verbose_name_plural': '奉獻支出帳務項目管理',
            },
        ),
        migrations.AlterModelOptions(
            name='family',
            options={'verbose_name': '家族', 'verbose_name_plural': '家族管理'},
        ),
        migrations.AlterField(
            model_name='family',
            name='introduce',
            field=models.TextField(blank=True, verbose_name='家族簡介'),
        ),
        migrations.AlterField(
            model_name='family',
            name='name',
            field=models.CharField(max_length=30, verbose_name='家族名稱'),
        ),
        migrations.AlterField(
            model_name='member',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='lightup.family', verbose_name='家庭'),
        ),
        migrations.CreateModel(
            name='Enroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('backup', models.TextField(blank=True, verbose_name='備註')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrolls', to='lightup.course', verbose_name='報名訓練課程')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_enrolls', to='lightup.member', verbose_name='報名會友')),
            ],
            options={
                'verbose_name': '訓練課程報名',
                'verbose_name_plural': '訓練課程報名管理',
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('record_date', models.DateField(verbose_name='記錄歸屬日期')),
                ('name', models.CharField(max_length=30, verbose_name='內容')),
                ('account', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='金額')),
                ('backup', models.TextField(blank=True, verbose_name='備註')),
                ('donate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donate_incomes', to='lightup.donate', verbose_name='非會友奉獻')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_incomes', to='lightup.member', verbose_name='會友奉獻')),
                ('income_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='income_item_incomes', to='lightup.income_item', verbose_name='帳務分類')),
            ],
            options={
                'verbose_name': '奉獻收入',
                'verbose_name_plural': '奉獻收入管理',
            },
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('record_date', models.DateField(verbose_name='記錄歸屬日期')),
                ('name', models.CharField(max_length=30, verbose_name='內容')),
                ('account', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='金額')),
                ('backup', models.TextField(blank=True, verbose_name='備註')),
                ('outcome_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outcome_item_outcomes', to='lightup.outcome_item', verbose_name='帳務分類')),
            ],
            options={
                'verbose_name': '聖工支出',
                'verbose_name_plural': '聖工支出管理',
            },
        ),
    ]
