# Generated by Django 5.2.8 on 2025-12-01 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lightup', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='family',
            options={'verbose_name': '家庭', 'verbose_name_plural': '家庭管理'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': '會友', 'verbose_name_plural': '會友管理'},
        ),
        migrations.AlterField(
            model_name='family',
            name='backup',
            field=models.TextField(blank=True, verbose_name='備註'),
        ),
        migrations.AlterField(
            model_name='family',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='建立時間'),
        ),
        migrations.AlterField(
            model_name='family',
            name='introduce',
            field=models.TextField(blank=True, verbose_name='家庭簡介'),
        ),
        migrations.AlterField(
            model_name='family',
            name='name',
            field=models.CharField(max_length=30, verbose_name='家庭名稱'),
        ),
        migrations.AlterField(
            model_name='family',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新時間'),
        ),
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.CharField(max_length=60, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='member',
            name='agreement',
            field=models.BooleanField(default=False, verbose_name='是否同意個資條款'),
        ),
        migrations.AlterField(
            model_name='member',
            name='ananias',
            field=models.CharField(max_length=30, verbose_name='授洗人員'),
        ),
        migrations.AlterField(
            model_name='member',
            name='backup',
            field=models.TextField(blank=True, verbose_name='備註'),
        ),
        migrations.AlterField(
            model_name='member',
            name='born',
            field=models.DateField(verbose_name='出生日期'),
        ),
        migrations.AlterField(
            model_name='member',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='建立時間'),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.CharField(max_length=60, unique=True, verbose_name='電子郵件'),
        ),
        migrations.AlterField(
            model_name='member',
            name='emergency_contact',
            field=models.CharField(max_length=30, verbose_name='緊急聯絡人'),
        ),
        migrations.AlterField(
            model_name='member',
            name='emergency_tel',
            field=models.CharField(max_length=30, verbose_name='緊急聯絡電話'),
        ),
        migrations.AlterField(
            model_name='member',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='lightup.family', verbose_name='家庭'),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('男', '男'), ('女', '女')], max_length=10, verbose_name='性別'),
        ),
        migrations.AlterField(
            model_name='member',
            name='job',
            field=models.CharField(choices=[('學生', '學生'), ('軍人', '軍人'), ('公務員', '公務員'), ('教師', '教師'), ('農', '農'), ('漁', '漁'), ('公務', '公務'), ('服務業', '服務業'), ('技工', '技工'), ('自由業', '自由業'), ('家管', '家管'), ('退休', '退休'), ('其他', '其他')], max_length=30, verbose_name='職業'),
        ),
        migrations.AlterField(
            model_name='member',
            name='marriage',
            field=models.CharField(choices=[('未婚', '未婚'), ('已婚', '已婚'), ('離婚', '離婚'), ('喪偶', '喪偶')], max_length=10, verbose_name='婚姻狀況'),
        ),
        migrations.AlterField(
            model_name='member',
            name='mobile',
            field=models.CharField(max_length=20, unique=True, verbose_name='手機'),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=30, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='member',
            name='personal_id',
            field=models.CharField(max_length=15, unique=True, verbose_name='身分證'),
        ),
        migrations.AlterField(
            model_name='member',
            name='personal_pic',
            field=models.ImageField(blank=True, null=True, upload_to='member_pics/', verbose_name='個人大頭照'),
        ),
        migrations.AlterField(
            model_name='member',
            name='reborn',
            field=models.DateField(verbose_name='受洗日期'),
        ),
        migrations.AlterField(
            model_name='member',
            name='status',
            field=models.CharField(choices=[('慕道友', '慕道友'), ('受洗', '受洗'), ('轉入', '轉入'), ('轉出', '轉出'), ('離堂', '離堂')], max_length=10, verbose_name='會友狀態'),
        ),
        migrations.AlterField(
            model_name='member',
            name='tribe',
            field=models.CharField(choices=[('阿美族', '阿美族'), ('泰雅族', '泰雅族'), ('排灣族', '排灣族'), ('布農族', '布農族'), ('卑南族', '卑南族'), ('魯凱族', '魯凱族'), ('鄒族', '鄒族'), ('賽夏族', '賽夏族'), ('達悟族', '達悟族'), ('邵族', '邵族'), ('噶瑪蘭族', '噶瑪蘭族'), ('太魯閣族', '太魯閣族'), ('撒奇萊雅族', '撒奇萊雅族'), ('賽德克族', '賽德克族'), ('拉阿魯哇族', '拉阿魯哇族'), ('卡那卡那富族', '卡那卡那富族')], max_length=10, verbose_name='族別'),
        ),
        migrations.AlterField(
            model_name='member',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新時間'),
        ),
    ]
