# Generated by Django 5.2.8 on 2025-12-01 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=30)),
                ('introduce', models.TextField(blank=True)),
                ('backup', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('personal_id', models.CharField(max_length=15, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(choices=[('男', '男'), ('女', '女')], max_length=10)),
                ('born', models.DateField()),
                ('address', models.CharField(max_length=60)),
                ('mobile', models.CharField(max_length=20, unique=True)),
                ('email', models.CharField(max_length=60, unique=True)),
                ('marriage', models.CharField(choices=[('未婚', '未婚'), ('已婚', '已婚'), ('離婚', '離婚'), ('喪偶', '喪偶')], max_length=10)),
                ('emergency_contact', models.CharField(max_length=30)),
                ('emergency_tel', models.CharField(max_length=30)),
                ('reborn', models.DateField()),
                ('ananias', models.CharField(max_length=30)),
                ('personal_pic', models.ImageField(blank=True, null=True, upload_to='member_pics/')),
                ('status', models.CharField(choices=[('慕道友', '慕道友'), ('受洗', '受洗'), ('轉入', '轉入'), ('轉出', '轉出'), ('離堂', '離堂')], max_length=10)),
                ('tribe', models.CharField(choices=[('阿美族', '阿美族'), ('泰雅族', '泰雅族'), ('排灣族', '排灣族'), ('布農族', '布農族'), ('卑南族', '卑南族'), ('魯凱族', '魯凱族'), ('鄒族', '鄒族'), ('賽夏族', '賽夏族'), ('達悟族', '達悟族'), ('邵族', '邵族'), ('噶瑪蘭族', '噶瑪蘭族'), ('太魯閣族', '太魯閣族'), ('撒奇萊雅族', '撒奇萊雅族'), ('賽德克族', '賽德克族'), ('拉阿魯哇族', '拉阿魯哇族'), ('卡那卡那富族', '卡那卡那富族')], max_length=10)),
                ('job', models.CharField(choices=[('學生', '學生'), ('軍人', '軍人'), ('公務員', '公務員'), ('教師', '教師'), ('農', '農'), ('漁', '漁'), ('公務', '公務'), ('服務業', '服務業'), ('技工', '技工'), ('自由業', '自由業'), ('家管', '家管'), ('退休', '退休'), ('其他', '其他')], max_length=30)),
                ('lecture', models.CharField(choices=[('學前', '學前'), ('小學', '小學'), ('國中', '國中'), ('高中', '高中'), ('大專', '大專'), ('大學', '大學'), ('碩士', '碩士'), ('博士', '博士'), ('其他', '其他')], max_length=20, verbose_name='學歷')),
                ('agreement', models.BooleanField(default=False)),
                ('backup', models.TextField(blank=True)),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='lightup.family')),
            ],
        ),
    ]
